services:
  mysql-prod:
    image: mysql:8.0
    container_name: mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_prod_data:/var/lib/mysql
      - ./mysql-prod-init:/docker-entrypoint-initdb.d

  mysql-uat:
    image: mysql:8.0
    container_name: mysql-uat
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_uat_data:/var/lib/mysql
      - ./mysql-uat-init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

volumes:
  mysql_prod_data:
  mysql_uat_data:
