networks:
  zuufa:
    external: true

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    profiles: ["prod"]
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - zuufa
  redis-uat:
    image: redis:7-alpine
    container_name: redis-uat
    profiles: ["uat"]
    restart: unless-stopped
    ports:
      - "6479:6379"
    volumes:
      - redis_uat_data:/data
    command: redis-server --appendonly yes
    networks:
      - zuufa
volumes:
  redis_data:
  redis_uat_data:
